---
- name: Check Python Version on Windows Machines
  hosts: win
  gather_facts: false
  tasks:
    - name: Get Python Version
      win_shell: python --version
      register: python_version_output

    - name: Display Python Version
      debug:
        var: python_version_output.stdout_lines
