---
- name: Install Python on Windows Machines
  hosts: win
  gather_facts: false
  tasks:
    - name: Install Chocolatey
      win_shell: |
        Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

    - name: Install Python
      win_chocolatey:
        name: python
        state: present
